### ISSUE TITLE
Don't use width 100% on registration form fields

### ISSUE THREAD

**Issue by vtemian** [zalmanu/project-spartan#189]
A fix width looks better

**Comment by Fineas** [comment]
can you be a little more specific?
I used 100% for responsiveness.

**Comment by vtemian** [comment]
You can wrap the form in a div and control its width with col-xs-<number> and col-md-<number> to make it responsive. Maybe it helps: http://www.w3schools.com/bootstrap/bootstrap_forms_sizing.asp
![form](https://cloud.githubusercontent.com/assets/639771/17227916/634ed266-5519-11e6-9a08-76a3ee54ade7.png)
