### ISSUE TITLE
Missing faq page

### ISSUE THREAD

**Issue by vtemian** [zalmanu/project-spartan#195]
I was on contact page, clicked on faq -> 404
http://spartantasks.com/contact/faq.html

**Comment by emanuelcovaci** [comment]
http://spartantasks.com/contact/
http://spartantasks.com/faq/

Sunt url-uri diferite pentru http://spartantasks.com/contact/faq.html sigur o sa primesti 404 e normal 

Mie imi merge sunt pe /contact si daca dau pe faq merge

**Comment by vtemian** [comment]
Mie nu imi merge. Daca merg pe http://spartantasks.com/contact/ si pe urma dau click pe link-ul spre faq din descriere, ma duce la http://spartantasks.com/contact/faq.html

**Comment by emanuelcovaci** [comment]
Ce chestie...chiar am mai incercat odata  acum si ma duce pe http://spartantasks.com/faq/
