### ISSUE TITLE
Google maps not working on create post form

### ISSUE THREAD

**Issue by vtemian** [zalmanu/project-spartan#202]
```
This page didn't load Google Maps correctly. See the JavaScript console for technical details.
```
```js?sensor=false&libraries=places:95 You have included the Google Maps API multiple times on this page. This may cause unexpected errors.```

**Comment by Fineas** [comment]
We still have to fix the key problem

**Comment by emanuelcovaci** [comment]
Merge acum Google maps pe online

**Comment by Fineas** [comment]
super, dar warningul cu cheia tot apare
