### ISSUE TITLE
Show max bid on post page (spartan screen)

### ISSUE THREAD

**Issue by vtemian** [zalmanu/project-spartan#212]

**Comment by emanuelcovaci** [comment]
Am ales sa nu facem asta dintr-un motiv foarte simplu.
De ex Vlad spune ca e dispus sa plateasca max 200 lei pentru un tasks.
Daca vad spartani aceasta suma o sa liciteze cu un pret foarte aproape de maxim.
Daca nu aratam suma sunt sanse sa primeasca oferte mult mai ieftine si care sa-i convina mai mult

**Comment by vtemian** [comment]
Nu e foarte ok asa fiindca nu mai ai concurenta si acel max bid atunci e pointless daca oricum oamenii nu il stiu.
E super frustrant pentru oameni sa faca un bid si pe urma nu e valid.
De exemplu:
De ex Vlad spune ca e dispus sa plateasca max 200 lei pentru reparat parchetul din dormitor, dar nu arata.
Un mester intra, vede anuntul, dar el nu repara parchetul sub 500 lei, asa ca liciteaza 700 lei. E prea scump. Scade la 650, la 600, la 550, la 500, se enerveaza si pleaca pentru ca el nu poate sa liciteze.

**Comment by emanuelcovaci** [comment]
Hmm
Atunci putem sa afisam o suma maxim ,dar peste care sa se poata licitat totusi
Ca poate angajatorul nu estimeaza bine lucrarea si nu o sa primeasca oferte ca a pus o limita de pret prea mica
