### ISSUE TITLE
[spartan] show mean bid on post

### ISSUE THREAD

**Issue by vtemian** [zalmanu/project-spartan#216]
![freelancer](https://cloud.githubusercontent.com/assets/639771/17229797/ea8ffb26-5521-11e6-9b2b-18af45d9a1ea.png)

**Comment by emanuelcovaci** [comment]
Am facut backend-ul pentru max bid si pentru Average bid mai am nevoie doar de frontend de la tine fineas 
![suma](https://cloud.githubusercontent.com/assets/11509775/17273565/6232e46c-56c2-11e6-92e9-789b23f14c4a.png)
